# Introduction to Python

If you are viewing this notebook on `datahub.berkeley.edu`, you should have everything you need. If you are running this anywhere else, you will need Python 3 and the core Jupyter packages, as well as `numpy`, `scipy`, and `matplotlib`, which are standard packages that should come with your Jupyter installation.

### Contents
- [Introduction](#intro)
- [A glorified calculator](#calc)
- [Types of things](#types)
- [Functions and variables](#fn)
- [Lists, tuples, etc.](#lists)
- [Classes](#classes)
- [Control flow](#cflow)
- [NumPy](#numpy)
- [Jupyter notebooks](#jupyter)

<a name="intro"></a>
### Introduction
#### Welcome to programming
An integral part of the physicist's toolkit is the computer. A computer is a physical device designed in such a way that the physical states of the system, and the relationships between them, can be mapped to those of any other physical systems. Thus we can simulate physical systems by identifying them with that of a computer. This mapping is so powerful in fact that it is more effective to think of the computer as a mathematical system rather than a physical one. The mathematics of computers, called computer science, is a rich field which connects seamlessly with physics in areas like (quantum and classical) information theory and complexity theory. Many physicists subscribe to some kind of notion of digital philosophy, in which the primary entities of the universe, the physical things, are nothing more than information ("it from bit/qubit"). In this viewpoint, computer science and physics are literally identical. It is not surprising then, that people interested in physics are often also interested in mathematics and computer science. However here we use computers only as tools that enable greater physical insight and understanding, and so for us right now they are a means to an end rather than an end itself.

You will be learning programming for physics in a language called Python. As such we will only teach you what you're likely to need to know. Thus while we won't talk about Turing machines or complexity classes, we recommend that you take some CS classes or use some of the extensive resources available online to learn more about this rich and interesting field of study.

Computers are mathematical systems which we can program. We can create mathematical objects, and define the rules that determine how they behave. Physical systems also follow rules. By encoding those rules into a program, we can use the physical system that is a computer to simulate a vast array of other physical systems.

If we compute things exactly using abstract mathematical objects as we would on paper, this is called __symbolic__ computing. We'd recommend [Mathematica](https://software.berkeley.edu/mathematica) for symbolic computing, but Python also has [a package](https://www.sympy.org/en/index.html) for it. Symbolic computing basically does the math for you because some mathematicians have codified into a program the usual rules of manipulation of mathematical expressions.

While you are welcome to use symbolic computation, this is not the kind of computing we shall be doing here. We shall be doing __numerical__ computing, in which we approximate numbers to representations on a computer. Since a digital computer only has a finite level of accuracy (discussed further below), this process is not exact and does contain error. Sometimes one must be careful that the errors do not propagate and that our answers are not affected by it. 

#### Motivation
Why use computers? Can't we use good old-fashioned pen and paper to get exact answers instead of numerical approximations? Here are some things that are easy numerically, but extremely tedious if not untractable analytically:

- transcendental equations
- high-dimensional statistics
- solving differential equations (Navier-Stokes: is fluid dynamics solved?)
- data analysis
- series expansions
- evaluating functions
- integration
- basic arithmetic (what's $67+313^{344}-13*12 \mod 235$?)

In this series of introductory notebooks, we shall do all of the above using standard packages in Python. 

The rest of this notebook is an introduction to programming in Python. Each section introduces you to programming concepts and/or shows you how to efficiently implement schemes in Python. If you are familiar with Python, you might want to skip this notebook and move on to the next one which introduces you to scientific computing in Python. If you are familiar with programming but not Python, we'd recommend that you go through the relevant parts of the notebook to get familiar with Python quirks and syntax.

#### Python vs other languages
The Physics department has decided to use Python since it is the most commonly used language for applications in physics. Python is a _high-level_ language, which means that Python itself is written in a _low-level language_ like C, which itself is written in the binary instruction language understood by the computer. Thus when you run a Python program, it is first compiled to a C program. This C program is then compiled to machine instructions, which are then executed. A higher-level language allows you to do more things without having to write as much code, and not worry about the details of how things work under the hood. A lower-level language will be more verbose, but it gives you the ability to choose exactly how things are implemented, and thus allows you to make your code run faster. Since we use Python, our code will typically be shorter but slower than the equivalent code in a lower-level language. 

<a name="calc"></a>
### A glorified calculator

You can do all the usual arithmetic operations with Python. You can edit and press `shift` + `enter` to evaluate each of the cells below. Feel free to create a new notebook or additional cells using the + icon in the taskbar on top of the page to play around.

Addition

In [1]:
5+2

7

Subtraction

In [2]:
6-8

-2

Multiplication

In [3]:
4*2.5

10.0

Division

In [4]:
32/6 #this is a comment

5.333333333333333

Integer division (quotient)

In [5]:
32//6. #everything after the '#' is ignored by Python

5.0

Modulus (remainder)

In [6]:
32%6.

2.0

Exponentiation (be careful not to use `^`, that means [bitwise `XOR`](https://en.wikipedia.org/wiki/Bitwise_operation#XOR))

In [7]:
2**10

1024

You can also compare objects

In [8]:
3 < 4, 5 == 5.0, 32 >= 33

(True, True, False)

It follows the usual order of operations

In [9]:
4**3/2+1%5, (4**(3/2)+1)%5 #use parentheses where required.

(33.0, 4.0)

The full list of in-built Python operators can be found in the [relavant Python documentation](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex). In general, whenever you are using something written by somebody else, you should make sure you know what it is doing, e.g. what inputs to give a function and what outputs to expect. This is the purpose of __documentation__, and using documentation is an essential programming skill. Documentation and [stack overflow](https://stackoverflow.com/) will be your greatest friends in your quest to learn Python. Since we introduce you to all of Python in one notebook, we mention a lot of things without explaining them in depth. We will at first provide links to documentation, but later will expect you to use the extensive materials available online by yourself. 

<a name="eqn"></a>
### Types of things
These are many different types of primitive objects in Python. As you saw above, the most commonly used built-in types are integers (`int`) and floating-point numbers (`float`). Other commonly used types are pieces of text, called strings (`str`), and binary true/false objects called [Booleans](https://en.wikipedia.org/wiki/Boolean_algebra) (`bool`). Python has a built-in function called `type()` that tells you the type of a given object.

In [10]:
type(1), type(1.), type(True), type("hello")

(int, float, bool, str)

`int`s are exact and Python 3 automatically resizes the data allotted to each int so that it can store an arbitrarily large positive or negative integer. On the other hand, `float`s are __not exact__. Essentially floating-point numbers are binary fractions multiplied by a scale. Typically Python uses 64 bits for floats, which are represented as $n=\text{(53-bit integer)}\times 2^{\text{(11-bit integer)}-52}$. Thus there are 53 bits of precision, meaning that the float $f$ represents all numbers in a range of $2^{-53}f$. When subtracting floats that are very close to each other (e.g. taking derivatives), error that was intially a factor of $10^{-16}$ might scale up dramatically. The largest and smallest numbers floats can store are $2^{-2^{10}-52}$ and $2^{2^{10}-1}$ (we lose 1 bit to the sign of each integer). Trying to store smaller or larger numbers results in underflow or overflow respectively (but sometimes you can work in log space). Ultimately, since they are represented using 64 bits, there are only $2^{64}$ floats. This kind of thing is unavoidable when using a discrete system like a digital computer to model or represent a continuous system like the number line. Since these representational errors can compound, comparing floats is a bit tricky. For more information, read the [Python tutorial](https://docs.python.org/3/tutorial/floatingpoint.html).

In [11]:
2**1024 #python ints rescale as much as memory allows

179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424865485276302219601246094119453082952085005768838150682342462881473913110540827237163350510684586298239947245938479716304835356329624224137216

When a number becomes too large or too small to be a represented by a float, e.g. when performing repeated multiplications or divisions, this is known as _overflow_ or _underflow_ respectively.

In [12]:
2.**1024 #overflow

OverflowError: (34, 'Numerical result out of range')

In [13]:
1.999999*2.**1023, 2*2.**1023

(1.7976922360157486e+308, inf)

In [14]:
2**-1074, 1.99999999*2**-1075

(5e-324, 0.0)

In [15]:
2**-53, 1.+2**-52, 1.+2**-53 #float precision

(1.1102230246251565e-16, 1.0000000000000002, 1.0)

In [16]:
2**64 #total number of floats

18446744073709551616

In [17]:
3*0.1, 3*0.1 == 0.3 #in practice, we can check if 2 floats are within some small tolerance from each other; more on this later.

(0.30000000000000004, False)

Here's a handy way to input large or small `float`s:

In [18]:
1e-2, 1.4e3, 1.8e0 #use e to set an integer exponent, e.g. 3.3e-5 =  3.3 * 10**-5

(0.01, 1400.0, 1.8)

Python automatically casts one type to another when required. Typically the casting heirarchy preserves information. For more information, read the [docs](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex).

In [19]:
type(5*2), type(5*2.), type(5/2), type(5//2), type(1.+False)

(int, float, float, int, float)

Of course, this doesn't always work:

In [20]:
1+"2"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

You can also explicitly convert some types to others using built-in functions that are rather intuitively named:

In [21]:
str(5.4), bool(-45.2), float(6), int(6.9), float("587e-10")

('5.4', True, 6.0, 6, 5.87e-08)

Of course, this doesn't always work.

Python also has complex numbers, initialised by the special letter `j` written at the end of a number (`int` or `float`), which plays the role of $i\equiv\sqrt{-1}$.

In [22]:
type(1j), abs(.4+.3j), 1==1+0j, (3+2j).real, (3+2j).imag

(complex, 0.5, True, 3.0, 2.0)

There's also a special constant called `None` that is sometimes used to denote a lack of information.

In [23]:
type(None)

NoneType

<a name="fn"></a>
### Functions and variables

Functions are types of objects which return objects when given objects. They are functions as we think of them mathematically. Python has several built-in functions, like `type()` and the ones to convert type that we saw in the previous section. We can also define our own functions. Here's the function definition for $f(x)=x^2$.

In [24]:
def f(x): #this is the function definition
    """Returns the square of x""" #this is the docstring. it is documentation that specifies what the function does.
    #this is the body of the function. you can use any of the arguments (in this case, x) here
    #the function ends when the indented block ends or when it hits a return
    #the editor will automatically indent after a valid function declaration, but you will sometimes have to unindent manually.
    return x**2 #function execution ends and x**2 is passed on to the thing that called the function
#function definition ended. no longer indented
#to learn how functions are executed, google 'call stack'

In [25]:
f(4) #this is a function call. The code written in the function definition is only executed when it is called

16

To obtain information about a function, use `?`.

In [26]:
f?

In [27]:
str?

In most programming languages, one has to specify the type of each argument accepted by the function. For example, we would have to specify that `x` in the function above is e.g. a `float`. However, Python is __untyped__. In Python, anything can be passed on to the function, and so one has to be careful that the function works as expected for all the types it is called on. One common beginners' mistake is for people to pass lists to functions expecting single values. If other people are going to be using your code, you can enforce preconditions on your arguments using the statements `assert` and/or `raise`.

In [28]:
f(True)

1

In [29]:
f("a") #Since python is untyped, python functions differ from mathematical functions in that they lack explicit domains and ranges

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

Keep in mind that functions don't have to return anything. If Python sees an unindented block before a `return`, it will end the function execution and implicitly return `None`. 

We can also create variables that can take on temporary values. Again, in Python, unlike most other languages, variables are untyped. Thus a variable that starts off as an `int`, for example, might get reassigned to a `str`.

In [30]:
x = 5 #this is an assignment. The variable x now has the value 5

In [31]:
x #can access variable in any cell executed after the one it was defined in

5

In [32]:
x = "ab"+"cd" #assign new value. old value lost.

In [33]:
x

'abcd'

In [34]:
del x #delete variable

In [35]:
x

NameError: name 'x' is not defined

Variables like `x` in the cell above are _global_ variables. They can be referenced anywhere in the notebook. However, variables defined inside function definitions are called _local_ variables. They can only be accessed within the body of the function, and are lost when the function execution ends. If a global variable has the same name as the argument to a function or to a local variable, the global variable cannot be accessed within the body of the function. In general, try to avoid namespace collisions.

In [36]:
x = 5 #global variables
z = 6
y = -1

def g(x,y):
    #global variables x and y cannot be accessed here because they have same names as arguments
    z = x + y #defines new local variable in terms of arguments. now global variable z is unchanged but cannot be accessed
    return f(z) #uses local variable

g(1,2), z, f(z), x, y, f(x+y) #this is outside body of function. global vriables can be accessed.

(9, 6, 36, 5, -1, 16)

While functions can access global variables, this is considered bad programming practice. One should pass the function everything it needs as an argument, so that the function can run in any environment and no global variables need to be defined. Similarly, one can change global variables by scoping it using `global`, but one should instead return everything required.

In [37]:
def bad_fn(x):
    return x + z #using global variable z and argument x

bad_fn(1), x, z

(7, 5, 6)

In [38]:
z = None #this breaks the function
bad_fn(1)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

While we have only shown you functions with 1 or 2 arguments so far, you can define functions with 0 or more arguments. In Python you can also define some arguments to be optional, and assign it a default value in the function definition. These arguments are known as keywords. As an example, let's consider the problem of testing two `float`s for equality. 

In [39]:
def float_equal(float1, float2, tolerance=1e-6):
    return abs(float1-float2) <= tolerance

float_equal(0.1*3, 0.3), float_equal(3, 3+5e-7), float_equal(3, 3+5e-7, 1e-7)

(True, True, False)

Arguments can be given using the name of the argument, in which case the order of arguments doesn't matter. Keywords must always follow the regular arguments though.

In [40]:
float_equal(0.1*3, 0.3, 1e-10), float_equal(0.1*3, 0.3, tolerance=1e-10), float_equal(tolerance=1e-10, float2=0.3, float1=0.1*3) #these are all equivalent.

(True, True, True)

Functions are just another type of object. Thus we can use functions as arguments to functions, or have functions that return functions. Here is one that does both:

In [41]:
type(f)

function

In [42]:
def add_five(fn):
    def g(x):
        return fn(x)+5
    return g

h = add_five(f)
add_five, h, f(3), h(3)

(<function __main__.add_five(fn)>,
 <function __main__.add_five.<locals>.g(x)>,
 9,
 14)

A popular computer science paradigm is functional programming, in which all data types are functions. The analogous field of math is known as $\lambda$-calculus. In this spirit, Python offers a way to create anonymous functions in one line using the `lambda` command. For example, the command `lambda arg1, arg2: arg1+arg2` creates a function that takes two arguments and returns their sum. We can assign this object to a variable, e.g. `f = lambda arg: value`, which is equivalent to `def f(arg): return value`.

In [43]:
f = lambda x: x**2 #this is equivlent to the previous definition of f

def add_five(fn): #this is equivalent to the previous definition of add_five
    return lambda x: fn(x)+5

add_five = lambda fn: lambda x: fn(x)+5 #this is also equivalent to the previous definition of add_five

<a name="lists"></a>
### Lists, tuples, etc.

Lists are ordered collections of objects. Lists are demarcated by `[]` and entries are separated by `,`.

In [44]:
type([]) #empty list

list

Since Python is untyped, different entries of the same list can have different types.

In [45]:
a = [1, "a", None, 0.7+7j, False]

Python has an in-built function `len()` which returns the number of entries (length) in a list (or list-like object).

In [46]:
len(a)

5

You can access entries using the index of each entry. In Python indices start from `0` and go to `n-1` for a list of length `n`. You can also index backwards, so `-x` is equivalent to `n-x`.

In [47]:
a[1], a[-2]

('a', (0.7+7j))

In [48]:
a[1] = "b" #change entry in list
a

[1, 'b', None, (0.7+7j), False]

One of Python's most useful features is list slicing, which generates sublists from a given list. `x[start:end:step]` returns a list containing every `step`th entry of `x` starting at `start` upto but not including `end`. The defaults for a list of length `n` are `start = 0`, `end = n`, and `step = 1`. (If `step < 0` then the defaults for `start` and `end` are changed accordingly.)

In [49]:
a[:] #all default: whole list

[1, 'b', None, (0.7+7j), False]

In [50]:
a[::] #same as above

[1, 'b', None, (0.7+7j), False]

In [51]:
a[1:3] #entries 1 through 3 (i.e. entries 1 and 2)

['b', None]

In [52]:
a[1::3] #every third entry starting at 1

['b', False]

In [53]:
a[-1] #last entry

False

In [54]:
a[-1:] #list of last entry onwards

[False]

In [55]:
a[:-1] #exclude last entry

[1, 'b', None, (0.7+7j)]

In [56]:
a[::-1] #whole list backwards

[False, (0.7+7j), None, 'b', 1]

In [57]:
a #original list is unchanged

[1, 'b', None, (0.7+7j), False]

Since a string is essentially a list of characters, slicing also works on strings.

In [58]:
b = "hello world"
b[2:-2] #without 2 characters each from front and back

'llo wor'

You might find the following methods useful. Consult documentation for more information.

In [59]:
a.append("a") #add entry to end of list
a #list is changed

[1, 'b', None, (0.7+7j), False, 'a']

In [60]:
del a[3] #remove entry by index
a

[1, 'b', None, False, 'a']

In [61]:
a.insert(2,"3") #add entry at specified index
a

[1, 'b', '3', None, False, 'a']

In [62]:
a.index("a") #find (first) index of a value
#this also works on strings

5

In [63]:
a.remove("a") #remove (first matching) entry by value
a

[1, 'b', '3', None, False]

You can add (concatenate) lists, which also generalises to integer multiplication.

In [64]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [65]:
5*[1,2]

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

The `in` keywords allows you to test for inclusion in a list-like object or string.

In [66]:
a = [1,2,3,4]
b = "abcd"
4 in a, "c" in b, [1,2,3] in a, "abc" in b

(True, True, False, True)

Python has an in-built function called `map()`, which allows you to conveniently execute a function on each element of a list. You might also want to look at `zip()`.

In [67]:
list(map(f, [1,2,3,4]))

[1, 4, 9, 16]

When a variable stores a primitive data type (like a float or bool), it stores it directly. However, when it stores a list, it stores a _pointer_ to a location in memory where the list is stored. Thus copying e.g. a float is easy, but copying a list involves copying each entry of the list. It also makes comparing objects difficult.

In [68]:
x = 5
y = x
x += 1 #shorthand for x = x + 1. Similar shorthands exist for -,*,/
x, y

(6, 5)

In [69]:
a = [1,2]
b = a
a.append("this is a not b")
a, b

([1, 2, 'this is a not b'], [1, 2, 'this is a not b'])

The `is` statement can be used to check if two variables point to the same object.

In [70]:
c = [1,2,"this is a not b"]
a == b, a == c, a is b, a is c

(True, True, True, False)

_Packages_ are libraries of code made public for people to use, so that people don't have to solve problems that have been solved before or write code that someone else has already written. Packages contain `.py` file(s) called _modules_ that can be imported using the `import` command. You can also write your own modules and import them in other pieces of Python code. You can also download packages from the internet. It is common to use a _package manager_ like [pip](https://pip.pypa.io/en/stable/quickstart/) or [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html). It is also quite easy to [publish](https://pypi.org/) a package that can can be downloaded using pip, or to publish your code to [GitHub](https://github.com/).

In addition to external packages that you can download, Python has several in-built modules. The in-built module `copy` provides tools to copy objects instead of pointers. The function `deepcopy()` works with lists of any depth (i.e. lists of lists of lists of...). Before using it, however, we must import it.

In [71]:
import copy

a = [1,2]
b = copy.deepcopy(a)
a.append("this is a not b")
a, b

([1, 2, 'this is a not b'], [1, 2])

In [72]:
a = [1,2]
b = a[:] #easy way using slicing (only for lists of primitives)
a.append("this is a not b")
a, b

([1, 2, 'this is a not b'], [1, 2])

Since we're only importing one function, it is better to use the following syntax to only import the function we need instead of the entire module.

In [73]:
from copy import deepcopy

a = [1,2]
b = deepcopy(a)
a.append("this is a not b")
a, b

([1, 2, 'this is a not b'], [1, 2])

Above, if we had written `from copy import *`, it would have imported everything from `copy` but without adding the name of the package to their names. This is known as a wildcard import, and it is dangerous because it can cause namespace collisions which can overwrite functions and variables that are already defined. You can also alias anything you import using `as`. For example, if you use `import copy as cp` you would then use `cp.deepcopy()`, or if you use `from copy import deepcopy as dc` you would then simply use `dc()`. You can also specify multiple objects to import by separating them with commas.

Tuples are essentially the same thing as lists, except they are immutable (can't be changed). They are demarcated by `()`.

In [74]:
type(()) #empty tuple

tuple

Tuples can be indexed and sliced like lists. They are the preferred data type of Python, since any comma-separated input automatically gets converted to tuples.

In [75]:
t = 1, None, "x"
type(t)

tuple

In [76]:
t

(1, None, 'x')

In [77]:
t[1], t[::-1]

(None, ('x', None, 1))

In [78]:
t[1] = True #immutable, have to create new tuple to edit

TypeError: 'tuple' object does not support item assignment

The `*` keyword can also be used to pass a tuple of arguments in a function, or retrieve any number of optional arguments to a function.

In [79]:
def example1(arg1, arg2):
    print(arg1, arg2)

args = "a","b"
example1(*args)

a b


In [80]:
def example2(arg, *args):
    print("arg:", arg)
    print("args:", args)
    print("args:", *args)

example2(1)
example2(2, *args)
example2(3, *t)

arg: 1
args: ()
args:
arg: 2
args: ('a', 'b')
args: a b
arg: 3
args: (1, None, 'x')
args: 1 None x


Python also supports tuple assignment, where you can economically set a tuple of variables to a tuple of values.

In [81]:
a, b, c = 1, None, "x"
type(a), type(b), type(c)

(int, NoneType, str)

In fact, we have been using tuples implicitly in almost all of the cells above. When you evaluate each cell (`shift`+`enter`), the Python kernel executes all the code in the cell, and returns the evaluation of the expression in the last line of the cell. Thus all the cells in which the last line is a list of things have returned tuples. However (and this was probably bad design to tell you this so late) we don't have to put things on the last line to see their output. We can display things at any point using the in-built function `print()`.

In [82]:
print("this is printed")
"this is returned" #note the difference between the two below

this is printed


'this is returned'

Python supports a [string formatting mini-language](https://docs.python.org/3/library/string.html#format-specification-mini-language) which enables you to conveniently output information in a readable format. Especially when debugging code, being able to easily read the values of variables is essential.

In [83]:
x = 1.2351
y = 1.2349
z = 4.9e-3
print(f"The value of x is {x:.2f}")
print("The value of y is {0:.2f}".format(y))
print("The value of z is %.2f"%z)

The value of x is 1.24
The value of y is 1.23
The value of z is 0.00


Dictionaries (`dict`s) are another commonly-used data type. Dictionaries consist of unordered pairs of objects, called _keys_ and _values_. They follow the format `{key1: value1, key2: value2, ...}`. Values can be accessed using the key similarly to how one may use an index for a list.

In [84]:
type({})

dict

In [85]:
d = {"a": f, 2: "f", True: ("j", "k")}
d["a"], d[2]

(<function __main__.<lambda>(x)>, 'f')

In [86]:
d[54.35332] = [5,0,-7,9] #adding a new entry
d

{'a': <function __main__.<lambda>(x)>,
 2: 'f',
 True: ('j', 'k'),
 54.35332: [5, 0, -7, 9]}

Dictionaries are useful to store data that consists of multiple fields, e.g. a university could be represented by `{"name": "UC Berkeley", location: (37.8719, -122.2585), "students": 42519, "private": False, "good departments": ["Physics", "EECS", "Political correctness"]}`.

In [87]:
list(d.keys()) #list of keys

['a', 2, True, 54.35332]

In [88]:
d.pop(True) #remove entry corresponding to key and return value removed

('j', 'k')

In [89]:
d

{'a': <function __main__.<lambda>(x)>, 2: 'f', 54.35332: [5, 0, -7, 9]}

`**` does for dicts what `*` does for tuples, for keyword arguments to functions.

In [90]:
def example3(a, b):
    print(a, b)

a = None, (5,-6)
b = {"b": (5,-6), "a": None}
example3(*a)
example3(**b)

None (5, -6)
None (5, -6)


In [91]:
def example4(arg, *args, **kwargs):
    print("arg:", arg)
    print("args:", args)
    print("kwargs:", kwargs)

example4(1)
example4(2, "abc", True, "def", keyword1="value1", k2="v2")

arg: 1
args: ()
kwargs: {}
arg: 2
args: ('abc', True, 'def')
kwargs: {'keyword1': 'value1', 'k2': 'v2'}


<a name="classes"></a>
### Classes

Lists and dicts are examples of complex data types, which can hold multiple pieces of information. These data types are useful generally, but different problems have different solutions. Lists are implemented as automatically-resizing arrays of contiguous memory. This means that (looking only at the [asysmptotic scaling](https://en.wikipedia.org/wiki/Big_O_notation) of the cost of operations) acessing elements is $\mathcal{O}(1)$ (i.e. is constant with array size), and inserting or removing items changes with the index, from $\mathcal{O}(1)$ at the end of the list to $\mathcal{O}(n)$ at the start. If you only need to insert and access things at the ends of a list, you might want to use one of the native Python `queue`s that are optimised for that. Dicts are implemented as hash tables, so accessing, inserting and removing is $\mathcal{O}(1)$, and so is checking for inclusion (which is $\mathcal{O}(n)$ for lists). Python also has native `set`s, which are essentially dicts with only keys.

Other data structures exist such as sorted lists (self-balancing binary trees), neural networks, decision trees, blockchain, etc. that are more efficient or convenient for different applications. A large part of CS is finding the most efficient way to solve a problem.

You can define data structures that are convenient for you by defining a `class`. Then you can create objects, which are _instances_ of the class. Using this paradigm is known as object-oriented programming. The class, as well as each object, may have associated variables and functions. These associated functions are called _methods_. If you get the hang of creating and using the classes you need, you will be able to program much more efficiently as you be less likely to have to write the same piece of code twice.

For example, if you wanted to create a class to store a 2D circle (e.g. for graphing purposes), you could do something like:

In [92]:
class Circle2D:
    pi = 3.14159 #class variable. of course, Python has a more accurate pi in the math module
    
    def __init__(self, centre=(0,0), radius=1): #constructor: this creates an instance given the arguments. self refers to instance
        #names like __this__ are special. consult docs if curious. names like _this are hidden (accessible only to methods of instance)
        self.x = centre[0] #these are instance variables
        self.y = centre[1]
        self.r = radius
    
    def centre_distance(self, point):
        return ((point[0]-self.x)**2+(point[1]-self.y)**2)**.5
    
    def contains_point(self, point): #instance method
        return self.centre_distance(point) <= self.r
    
    def area(self):
        return self.pi*self.r**2
    
    def shape(): #class method. note no reference to self
        return "round"

In [93]:
Circle2D.pi #accessing class variable

3.14159

In [94]:
Circle2D.shape() #class method

'round'

In [95]:
c = Circle2D(centre=(-8,4.5), radius=5) #creating instance
type(c)

__main__.Circle2D

In [96]:
print(c.x, c.y) #accessing instance variables
c.x, c.y =  0, 0 #changing them
print(c.x, c.y)

-8 4.5
0 0


In [97]:
c.centre_distance((-5,12)), c.contains_point((4,-3)), c.contains_point((5,.1)), c.area() #instance methods

(13.0, True, False, 78.53975)

In [98]:
c.pi #instance also has class variables

3.14159

In [99]:
c.shape()

TypeError: shape() takes 0 positional arguments but 1 was given

In [100]:
type(c).shape()

'round'

All the data types we've seen so far are classes, and we've seen quite a few of their methods and instance variables already. You can extend these, or any other, classes by defining a class that inherits the methods and properties of another class, using `class SubClass(ParentClass):`.

<a name="cflow"></a>
### Control flow

You can also change the way in which the code you write is executed. One example of this is an `if` statement. It executes code conditional on a Boolean.

In [101]:
if .38 == 1.9*.2: #play around with this condition
    print("true") #the indented block gets executed conditionally.
print("done") #this is always executed

true
done


In [102]:
def float_compare(float1, float2, tolerance=1e-10):
    if float_equal(float1, float2, tolerance):
        return "="
    elif float1 < float2: #else-if
        return "<"
    else: #since the function would have returned already we can replace the elif with an if and get rid of the else entirely
        return ">"

In [103]:
float_compare(6/9.003, 2/3.001)

'='

Python also has a _ternery operator_, which does an if-else in one line. The following example first checks if the point is in the circle. If it is, it returns zero, otherwise it computes and returns the distance.

In [104]:
distance_to_circle = lambda point, circle: 0 if circle.contains_point(point) else circle.centre_distance(point) - circle.r

In [105]:
distance_to_circle((-5,12),c), distance_to_circle((4,-3),c), distance_to_circle((0,1),c)

(8.0, 0, 0)

The `not` keyword negates a Boolean, so the above function is equivalent to:

In [106]:
distance_to_circle = lambda point, circle: (not circle.contains_point(point)) * (circle.centre_distance(point) - circle.r) #true=1 and false=0 for casting

In [107]:
distance_to_circle((-5,12),c), distance_to_circle((4,-3),c), distance_to_circle((0,1),c)

(8.0, 0.0, -0.0)

Using the in-built `max()` function, we can shorten the definition to:

In [108]:
distance_to_circle = lambda point, circle: max(circle.centre_distance(point) - circle.r, 0)

In [109]:
distance_to_circle((-5,12),c), distance_to_circle((4,-3),c), distance_to_circle((0,1),c)

(8.0, 0.0, 0)

You can also execute a piece of code multiple times if you put it in a __loop__. The `while` statement repeats a block of code until a Boolean turns `False`.

In [110]:
i = 0
while i < 10:
    i += 1
    print(i)
print("over")

1
2
3
4
5
6
7
8
9
10
over


For example, we can implement [Newton's method](https://en.wikipedia.org/wiki/Newton%27s_method) with the following code:

In [111]:
def newton_method(fn, x, epsilon=1e-5, tolerance=1e-10):
    while abs(fn(x)) >= tolerance: #while we are not at zero
        df = (fn(x+epsilon/2) - fn(x-epsilon/2))/epsilon #numerical estimate of derivative at x
        x -= fn(x)/df #change x
    #while loop ended, this means we are at zero
    return x

In [112]:
newton_method(f,3), newton_method(lambda x: x**2-1,3), newton_method(lambda x: x**2-1, -2)

(5.722045898299813e-06, 1.0, -1.000000000000001)

The statement `break` stops the execution of the loop, and `continue` skips the rest of the block only for the current iteration.

In [113]:
i = 0
while i < 10:
    i += 1
    if i%3 == 0:
        continue
    print(i)
print("over")

1
2
4
5
7
8
10
over


In [114]:
i = 0
while i < 10:
    i += 1
    if i == 5:
        break
    print(i)
print("over")

1
2
3
4
over


One has to be careful not to get caught in infinite loops. One will have to interrupt the kernel using `ctrl`+`D`, the right-click menu, or the button on the top of the window in such a situation. (There are several inputs that break Newton's method as well.)

In [115]:
i = 0
while i < 10000:
    if i**2 % 4 == 3: #curiosity: which numbers pass this if clause?
        print(i)
    #remember to increment!

KeyboardInterrupt: 

Sometimes it is more convenient to use `for` loops, which are essentially `while` loops with different syntax. This allows one to iterate through any `Iterator`, which is an object that enables iteration by implementing a method that returns the next item in iteration (in the example above it would increment `i`). List-like objects are _iterable_, which means they automatically support iteration. (Here the method automatically returns the next element of the list-like object.)

In [116]:
a = [1, "a", True, None, 4.5]
for item in a:
    print(item)

1
a
True
None
4.5


Iterating through a dict is equivalent to iterating through its keys.

In [117]:
d = {1: 3, "a": "b"}

for k in d:
    print(k,d[k])

1 3
a b


The inbuilt function `range(start, end, step)` creates an iterator with syntax that has the same meaning as in the context of slicing. This makes it easy to iterate a set number of times:

In [118]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


A range is not quite a list, though it can be converted to one. Iterators are better for loops because the entire list need never be created or stored in memory.

In [119]:
range(10), list(range(10))

(range(0, 10), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
type(range(10))

range

You can create your own iterator by defining a _generator_, which is a function that returns an iterator that runs code before and after `yield`ing values for iteration. 

In [121]:
def myGenerator(x):
    y=x**2
    yield 45
    if y==0:
        return 0 #stop iterating (return doesn't do anything)
    yield "x"
    yield x
    z=x-y
    while z<0:
        yield z
        z+=1
    yield y,x**z

iterator = myGenerator(3)
    
for i in iterator:
    print(i)

myGenerator, iterator, list(myGenerator(0))

45
x
3
-6
-5
-4
-3
-2
-1
(9, 1)


(<function __main__.myGenerator(x)>,
 <generator object myGenerator at 0x7f06cf6c5360>,
 [45])

In [122]:
iter = myGenerator(2)

In [123]:
next(iter) #run this a few times

45

Python also offers a one-line way to create lists using one-line loops, called _list comprehension_. It is often faster than writing out a proper loop. For example, if we wanted to create a list of every number squared from 0 to 10, we could do the following:

In [124]:
a = []
for i in range(10):
    a.append(i**2)
a

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [125]:
a = [i**2 for i in range(10)] #equivalent to the above loop
a

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

To see that list comprehensions are indeed slightly faster, you can import the `time()` function from the `time` module, which is useful for benchmarking code.

In [126]:
from time import time #is this bad? can we still access the time module?
#time() is function that gives current OS clock time in seconds
#we will use this to time executions to compare code

In [127]:
time() #run this a few times

1553738302.6779015

In [128]:
n = 10**6 #this is size of list, try changing this
start = time()
a = [] #first time the regular loop
for i in range(n):
    a.append(i**2)
checkpoint1 = time()
a = [i**2 for i in range(n)] #then time list comps
checkpoint2 = time()
a = list(map(f, range(n))) #lastly time the map() function
end = time()
print("List comprehension: %.4f sec\nLoop: %.4f sec\nMap function: %.4f sec" % (checkpoint2-checkpoint1, checkpoint1-start, end-checkpoint2))

List comprehension: 1.1762 sec
Loop: 0.9550 sec
Map function: 1.2269 sec


List comprehensions also support an `if` clause (as well as ternery operators described above).

In [129]:
#function that, given a Circle2D instance and a list of points, returns the sublist of points within the circle.
points_in_circle = lambda points, circle: [point for point in points if circle.contains_point(point)]

In [130]:
c = Circle2D() #circle has radius 1 and centre at (0,0) by default
points = [(1,0), (3,1), (-1,0.1), (0,0), (-0.5,0.5), (98,-23), (0.4, -0.3)]
points_in_circle(points, c)

[(1, 0), (0, 0), (-0.5, 0.5), (0.4, -0.3)]

You might also find the in-built function `enumerate()` useful.

In [131]:
a_list = [4, "a", (7,8,9), {3: 5, "g": None}, True]
for index, value in enumerate(a_list):
    print(index, value)

0 4
1 a
2 (7, 8, 9)
3 {3: 5, 'g': None}
4 True


Another useful control method is _recursion_, where a function calls itself. Here is a recursive implementation of Newton's method:

In [132]:
def newton_recursive(fn, x, epsilon=1e-5, tolerance=1e-10):
    if abs(fn(x)) < tolerance: #termination case
        return x
    #no need for else since function would have returned already otherwise
    df = (fn(x+epsilon/2) - fn(x-epsilon/2))/epsilon #numerical estimate of derivative at x
    x -= fn(x)/df #change x
    return newton_recursive(fn, x, epsilon, tolerance)

In [133]:
newton_recursive(f,3), newton_recursive(lambda x: x**2-1,3), newton_recursive(lambda x: x**2-1, -2)

(5.722045898299813e-06, 1.0, -1.000000000000001)

Again, it is easy to get stuck with infinite loops. To avoid this, remember to code a termination clause (i.e. a case where it returns something without calling itself), and to make progress towards termination at each function call. Recursion is usually aesthetically more pleasing than a loop, but is slightly slower due to the time taken to call each function. There are some problems for which recursion is better suited, particularly when the function calls itself multiple times per execution. Recursion is best suited for problems with self-similarity, which ties into concepts like fractals, scale invariance, and conformal symmetry in physics and mathematics. Such problems can typically be solved in $\mathcal{O}(\log(n))$ time. For example, if we wanted to create a simple discrete version of the [Cantor set](https://en.wikipedia.org/wiki/Cantor_set), we could use the following recursive function:

In [134]:
def cantor(level):
    if level == 0:
        return [1] #base unit
    level -= 1
    return cantor(level) + 3**level*[0] + cantor(level)

In [135]:
start = time()
print(cantor(3), len(cantor(15)), 3**15)
time()-start

[1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1] 14348907 14348907


6.501713037490845

Note that the above function can be implemented more efficiently using a loop as follows, but there are other problems where recursion is better.

In [136]:
def cantor(level):
    c = [1]
    for i in range(level):
        c = c + 3**i*[0] + c
    return c

In [137]:
start = time()
print(cantor(3), len(cantor(15)), 3**15)
time()-start

[1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1] 14348907 14348907


4.151990652084351

Recursion is usually slower becuase calling a function takes a certain amount of time, known as _function overhead_. Here is an example of two algorithms that both scale as $\mathcal{O}(n)$, but recursion is slower.

In [140]:
from random import shuffle #used to make random test case: more about this in next notebook

def recursive_max(arr):
    if len(arr)==1:
        return arr[0]
    x = len(arr)//2
    l = recursive_max(arr[:x])
    r = recursive_max(arr[x:])
    return l if l>r else r

def loop_max(arr):
    m=arr[0]
    for a in arr[1:]:
        if a>m:
            m=a
    return m

for i in range(0,6):
    test_array = list(range(10**i))
    shuffle(test_array) #mix up the order
    start=time()
    recursive_max(test_array)
    cp=time()
    loop_max(test_array)
    cp2=time()
    max(test_array)
    end=time()
    print("length: %d\trecursive: %.6f s loop: %.6f s python: %.6f"%(10**i,cp-start,cp2-cp,end-cp2))

length: 1	recursive: 0.000002 s loop: 0.000001 s python: 0.000001
length: 10	recursive: 0.000009 s loop: 0.000001 s python: 0.000001
length: 100	recursive: 0.000060 s loop: 0.000006 s python: 0.000002
length: 1000	recursive: 0.000621 s loop: 0.000034 s python: 0.000017
length: 10000	recursive: 0.006839 s loop: 0.000459 s python: 0.000195
length: 100000	recursive: 0.083436 s loop: 0.005609 s python: 0.002339


Sorting can be done recursively in $\mathcal{O}(n\log n)$ time. We compare our implementation to the default Python implementation, which is significantly faster because it isn't written in Python. The Python mantra of "don't reinvent the wheel" is a paradigm enforced by necessity. (If you want speed, don't use Python. Python is for convenience and not having to reimplement everything.)

In [141]:
def recursive_sort(arr):
    if len(arr)==0:
        return []
    x=[arr[0]]
    l=[]
    r=[]
    for a in arr[1:]:
        if a>x[0]:
            r.append(a)
        elif x[0]==a:
            x.append(a)
        else:
            l.append(a)
    return recursive_sort(l)+x+recursive_sort(r)

def loop_sort(arr): #try beating the recursive solution
    return sorted(arr) #currently returns Python's native (recursive) implementation

for i in range(0,6):
    test_array = list(range(10**i))
    shuffle(test_array)
    start=time()
    recursive_sort(test_array)
    cp=time()
    loop_sort(test_array) #default Python implementation, but feel free to test your own sort function
    end=time()
    print("length: %d\trecursive time: %.6f s\tloop time: %.6f s"%(10**i,cp-start,end-cp))

length: 1	recursive time: 0.000013 s	loop time: 0.000009 s
length: 10	recursive time: 0.000024 s	loop time: 0.000003 s
length: 100	recursive time: 0.000203 s	loop time: 0.000016 s
length: 1000	recursive time: 0.016509 s	loop time: 0.000191 s
length: 10000	recursive time: 0.029927 s	loop time: 0.002956 s
length: 100000	recursive time: 0.430543 s	loop time: 0.038537 s


As you learn Python, you might want to solve a few problems to get you familiar with things. We recommend doing the first ~30 problems on [Project Euler](https://projecteuler.net/) for this purpose.

There are a few other useful control structures. `try`-`except` lets you rescue a piece of code from an error, and `with` executes code between pre-defined code snippets. Consult docs for more info.

<a name="numpy"></a>
### NumPy

NumPy is one of the most commonly used packages in Python, and is the basis for most of the numerics in Python.

In [2]:
import numpy as np

NumPy has mathematical constants (which are also in the in-built `math` module).

In [143]:
np.pi, np.e #for physical constants, see scipy.constants

(3.141592653589793, 2.718281828459045)

The most useful feature of NumPy is the `ndarray` data type. This is a generalisation of a list to higher dimensions (a nested list). A list is essentially a vector, a list of lists, or a 2-D array, is a matrix. In general, an `ndarray` is nothing but a rank $n$ tensor. The function `array()` converts a list-like object to a NumPy array.

In [144]:
a = np.array([1])
type(a)

numpy.ndarray

There are many ways to construct arrays.

In [145]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [146]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [147]:
np.empty((20,3)) #uses whatever values happen to be in memory. be careful! 

array([[2.53425874e-316, 6.90047577e-310, 6.90047577e-310],
       [6.90047578e-310, 6.90047578e-310, 6.90047577e-310],
       [6.90047577e-310, 6.90047577e-310, 6.90047577e-310],
       [6.90047578e-310, 6.90047577e-310, 6.90047578e-310],
       [6.90047578e-310, 6.90047578e-310, 6.90047578e-310],
       [6.90047577e-310, 6.90047578e-310, 6.90047578e-310],
       [6.90047578e-310, 6.90047578e-310, 6.90047577e-310],
       [6.90047578e-310, 6.90047577e-310, 6.90047578e-310],
       [6.90047578e-310, 6.90047577e-310, 6.90047577e-310],
       [6.90047577e-310, 6.90047578e-310, 6.90047578e-310],
       [6.90047578e-310, 6.90047578e-310, 6.90047577e-310],
       [6.90047577e-310, 6.90047578e-310, 6.90047577e-310],
       [6.90047578e-310, 6.90047578e-310, 6.90047578e-310],
       [6.90047578e-310, 6.90047577e-310, 6.90047578e-310],
       [6.90047578e-310, 6.90047578e-310, 6.90047578e-310],
       [6.90047578e-310, 6.90047578e-310, 6.90047577e-310],
       [6.90047578e-310, 6.90047577e-310

In [148]:
np.eye(2) #identity matrix

array([[1., 0.],
       [0., 1.]])

In [149]:
np.arange(10) #numpy version of range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
np.diag(np.arange(4,-5,-2)) #diagonal matrix from 1d array

array([[ 4,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0, -2,  0],
       [ 0,  0,  0,  0, -4]])

In [151]:
np.linspace(0,1,21) #21 points evenly spaced between 0 and 1

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

We can perform operations on arrays as if they were just numbers, and these operations are applied element-wise on the arrays.

In [152]:
np.arange(10) + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [153]:
np.linspace(-3, 4, 50) * (np.arange(50)+1)

array([ -3.        ,  -5.71428571,  -8.14285714, -10.28571429,
       -12.14285714, -13.71428571, -15.        , -16.        ,
       -16.71428571, -17.14285714, -17.28571429, -17.14285714,
       -16.71428571, -16.        , -15.        , -13.71428571,
       -12.14285714, -10.28571429,  -8.14285714,  -5.71428571,
        -3.        ,   0.        ,   3.28571429,   6.85714286,
        10.71428571,  14.85714286,  19.28571429,  24.        ,
        29.        ,  34.28571429,  39.85714286,  45.71428571,
        51.85714286,  58.28571429,  65.        ,  72.        ,
        79.28571429,  86.85714286,  94.71428571, 102.85714286,
       111.28571429, 120.        , 129.        , 138.28571429,
       147.85714286, 157.71428571, 167.85714286, 178.28571429,
       189.        , 200.        ])

Each `ndarray` has an a `shape` attribute, which is a tuple that specifies the length of the array in each axis. The first axis corresponds to the outermost list of a nested list. You can change the shape of an array using `reshape()`.

In [154]:
a = np.arange(100)
print(a.shape)
a.reshape((-1,5,5)) #the -1 fills in for whatever value keeps the same total number of entries

(100,)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

NumPy arrays are indexed and sliced just like lists, except now indices can be specified for multiple axes at once.

In [155]:
a = [[1,2], [3,4]] #nested list
b = np.array(a) #convert list to ndarray
a[1][0], b[1,0]

(3, 3)

In [156]:
a[0][::-1], b[0,::-1]

([2, 1], array([2, 1]))

You can also slice arrays using an array of booleans, and using a list of indices.

In [157]:
a = np.arange(10)
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [158]:
a[a>5]

array([6, 7, 8, 9])

In [159]:
a = np.arange(16).reshape((4,4))
a[[1,0,3],2:]

array([[ 6,  7],
       [ 2,  3],
       [14, 15]])

Since arrays can be indices, one may chain indexing arrays ad infinitum.

In [41]:
N = 15 #try changing these and running the next few cells
x = 10

a = np.cos(np.linspace(0,x,N))**2
p = np.argsort(a) #this is a permutation array
p

array([11,  2,  7,  6,  3, 10, 12,  1, 14,  8,  5,  4,  9, 13,  0])

In [42]:
a, a[p] #p is the permutation that sorts a

(array([1.00000000e+00, 5.70872949e-01, 2.00918994e-02, 2.93077043e-01,
        9.21247140e-01, 8.26343065e-01, 1.71268441e-01, 8.04642355e-02,
        7.09796612e-01, 9.79011383e-01, 4.25999184e-01, 9.99329863e-06,
        4.32257752e-01, 9.80785635e-01, 7.04041031e-01]),
 array([9.99329863e-06, 2.00918994e-02, 8.04642355e-02, 1.71268441e-01,
        2.93077043e-01, 4.25999184e-01, 4.32257752e-01, 5.70872949e-01,
        7.04041031e-01, 7.09796612e-01, 8.26343065e-01, 9.21247140e-01,
        9.79011383e-01, 9.80785635e-01, 1.00000000e+00]))

In [43]:
p_inv = np.argsort(p) #inverse of permutation
p_inv

array([14,  7,  1,  4, 11, 10,  3,  2,  9, 12,  5,  0,  6, 13,  8])

In [44]:
p_inv[p], p[p_inv] #identity permutation

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]))

In [45]:
p[p][p][p][p][p][p][p] #p^8

array([14,  7,  1,  4, 11,  5,  3,  2,  9, 12, 10,  0,  6, 13,  8])

In [46]:
#find period of permutation by brute force

period = 1
identity = p[p_inv]
power = p
while np.any(power != identity):
    power = power[p]
    period += 1
period

18

In [48]:
p[p][p][p][p][p][p][p][p][p][p][p][p][p][p][p][p][p] #checking

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

`ndarrays` are more restrictive than Python arrays. They are __typed__, which means all the entries must be of the same type. (The data type is implicitly understood when creating the array, but can be explicitly set using the `dtype` keyword.) Also the shape of an array is immutable, so the length of each axis is fixed, whereas nested lists have no such restriction in native Python. 

In [160]:
a.dtype

dtype('int64')

Higher-dimensional lists aren't stored contiguously in memory, whereas ndarrays are, which makes them faster. Another thing to keep in mind when iterating over multi-dimensional arrays is that the arrays are stored in a 1-dimensional representation (flattened), so looping over the last axis is faster since adjacent values are adjacent in memory. 

In [161]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [162]:
n = 100
a = np.arange(n**3).reshape((n,n,n))
start=time()
for i in range(n):#loop last axis first
    for j in range(n):
        for k in range(n):
            a[k,j,i]
check = time()
for i in range(n):#loop last axis last
    for j in range(n):
        for k in range(n):
            a[i,j,k]
end = time()
print("Last axis first: %.3f sec\nLast axis last: %.3f sec"%(check-start, end-check))

Last axis first: 0.253 sec
Last axis last: 0.230 sec


NumPy is written in C, which is a lower-level programming language than Python. This makes it much more efficient than Python. Lower-level languages give one more control while higher-level languages give convenience by hiding things in __black boxes__, i.e. by allowing you to use functions without knowing how they're implemented. If you're interested in making things run as efficiently as possible so that you can simulate larger systems more accurately, you might want to open these black boxes and maybe implement some things yourself. However the convenience of Python comes from the large number of packages that efficiently solve a lot of problems in the large variety of fields in which Python is widely used. Thus the Python paradigm is to not to reinvent the wheel, but we also recommend being aware of how things work under the hood so that you know which tool is best for a given problem. It's a fine line, and it's up to you to decide how you want to code. If you find yourself re-implementing things to make them faster, you might want to use a lower-level language like C. (You can also use your own implementations of things in other languages within Python for the best of both worlds.)

Since NumPy data types are the same as those in C, they are different from native Python. Python resizes ints so that they can be arbitrarily large, whereas the default size of NumPy ints are 64 bits, which means they can store any value in `range(-2**63, 2**63)`. As for `float`s, NumPy also uses 64 bits by default, but has more options for precision (you can use 16, 32, 64, or 128 bits for floats or integers).

In [163]:
a=np.array([2])
a[0]**63, int(a[0])**63, a**64, 2**64 #signed integers in C wrap around at the half-way point, so it effectively implements modular/periodic arithmetic

(-9223372036854775808, 9223372036854775808, array([0]), 18446744073709551616)

To see just how much faster NumPy is, let's compare the same task as we did earlier with list comprehensions:

In [164]:
n = 10**6 #this is size of list, try changing this
start = time()
a = [i**2 for i in range(n)] #first time list comp
checkpoint = time()
a = np.arange(n)**2 #then time numpy
end = time()
print("List comprehension: %.4f sec\nNumPy: %.4f sec" % (checkpoint-start, end-checkpoint))

List comprehension: 0.6914 sec
NumPy: 0.3183 sec


Since NumPy is a lot faster, it is more efficient to reprogram all loops and list comprehensions into operations using NumPy arrays wherever possible. NumPy has implementations of standard functions like `exp()`, `log()`, `sin()`, `sqrt()`, etc. that work efficiently on arrays. NumPy and SciPy have virtually every tool that one might need, and have optimised these to work well with NumPy arrays. In order to rewrite all your loops into operations involving NumPy arrays to make your code more consistent, you might need to multiply arrays of different sizes. NumPy automatically handles this to some degree with a process known as _broadcasting_, which repeats an array of size 1 in a given dimension to match another array. We already saw an example of this when we added an `ndarray` to a scalar quantity. Consult docs for more info.

In [165]:
print(np.arange(16).reshape((4,4))+np.arange(4))
print(np.arange(16).reshape((4,4))+np.arange(4).reshape((4,1)))
print(np.arange(4).reshape((1,-1))+np.arange(4).reshape((-1,1)))

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


Once you get more familiar with NumPy, you might find that [the `einsum()` function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.einsum.html) is an easy way to input any array compuation.

<a name="jupyter"></a>
### Jupyter notebooks

The file you're interacting with is called a Jupyter notebook. Jupyter notebooks allow you to write, edit, and execute code in an interactive environemnt. A notebook is essentially a collection of cells. These cells can be executed in any order, but it is good practice, especially when sharing notebooks, to ensure that the cells are meant to be executed in order. You may want to familiarise yourself with the tools in the menus and toolbars.

You can also press `tab` while typing to have the editor suggest names of standard functions, methods, modules, etc. It will also suggest keywords when entering the arguments to a function from a standard package, which is helpful if you don't remember how to supply the arguments required.

In [ ]:
np.li #press tab
np.linspace(

Jupyter also uses IPython [_magics_](https://ipython.readthedocs.io/en/stable/interactive/magics.html), which are special functions accessed with `%`. For example, `%timeit` lets you time the execution of a line or cell of code without needing to import the `time` module. (Also see `%time`.)

In [166]:
%timeit np.sin(np.linspace(0,1,10**5)) #times execution of line

2.1 ms ± 33.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [167]:
%%timeit #times execution of cell
a = np.sin(np.linspace(0,1,10**5))
b = np.exp(a)+a**2

4.12 ms ± 43.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In addition to cells containing code, there are also `Markdown` cells, which allow you to typeset text. This cell is a Markdown cell, for example. Double-click to edit and press `shift`+`enter` to display these cells, just like code cells. You can change the type of a cell using the dropdown menu in the toolbar above. Markdown cells also support $\LaTeX$, which is used for typesetting equations like $f(x) = \int_0^x e^{-t^2}\:dt$. If you're planning to do physics or mathematics, you'd probably want to learn it at some point. [Overleaf](https://www.overleaf.com/) is an online LaTeX editor which also has tutorials (and Berkeley students also get free Pro accounts that make it easier to collaborate). Markdown has a variety of formatting options, and is a superset of HTML so supports all HTML formatting abilities. 

You can also programmatically generate Markdown, including LaTeX, from code cells.

In [168]:
from IPython.display import display,Markdown #IPython is the default interactive Python kernel for Jupyter

s = r"$${\rm equation}=\Gamma\!\left(\frac{1}{\alpha^2}\right)$$ <a href=''>HTML link</a> [Markdown link]()"
#the r escapes special charcters in the strings, try removing it.. (e.g. "\r" would usually be return, but r"\r" isn't)

print(Markdown(s))
display(Markdown(s))
s

<IPython.core.display.Markdown object>


$${\rm equation}=\Gamma\!\left(\frac{1}{\alpha^2}\right)$$ <a href=''>HTML link</a> [Markdown link]()

"$${\\rm equation}=\\Gamma\\!\\left(\\frac{1}{\\alpha^2}\\right)$$ <a href=''>HTML link</a> [Markdown link]()"

The following example illustrates the power of Jupyter notebooks. In it, a function takes arguments from the user using an interactive slider, and outputs an animated video, embedded inline into an HTML5 video tag (without saving the video). The example animates a simple simulation of random growth. <font color="red">Change?</font>

In [170]:
import random
import numpy as np
%matplotlib agg
from matplotlib import pyplot as plt
from IPython.display import HTML
from matplotlib.animation import FuncAnimation
from ipywidgets import interact_manual

class GrowthSim:
    def __init__(self,d=2):
        self.d=d
        self.growth=set()
        self.neighbours = set([tuple([0]*d)])
        self.bounds=np.zeros((d,2),dtype=int)
    
    def grow(self):
        turning = random.sample(self.neighbours,1)[0]
        self.neighbours.remove(turning)
        self.growth.add(turning)
        for i in range(self.d):
            if turning[i] > self.bounds[i,0]:
                self.bounds[i,0]=turning[i]
            elif turning[i] < self.bounds[i,1]:
                self.bounds[i,1]=turning[i]
            turning=list(turning)
            turning[i] += 1
            if tuple(turning) not in self.growth:
                self.neighbours.add(tuple(turning))
            turning[i] -= 2
            if tuple(turning) not in self.growth:
                self.neighbours.add(tuple(turning))
            turning[i] += 1
        return tuple(turning)
    
def frames(size,arr):
    sim=GrowthSim()
    while np.amax(np.abs(sim.bounds))<size:
        arr[tuple(np.array(sim.grow())+size)]=True
        yield arr

def update(im,disp):
    disp.set_data(im)
    return disp,

def anim(size=20,fps=20):
    tsize=2*size+1
    f = plt.figure(figsize=(6,6))
    dt = 1e3/fps
    arr=np.zeros((tsize,tsize),dtype=bool)
    disp = plt.imshow(arr,vmin=0,vmax=1)
    anim = FuncAnimation(f,update,frames(size,arr),fargs=(disp,),interval=dt,blit=True,save_count=tsize**2)
    %matplotlib inline
    return HTML(anim.to_jshtml())

interact_manual(anim,size=(3,100),fps=(1.,30.))

interactive(children=(IntSlider(value=20, description='size', min=3), FloatSlider(value=20.0, description='fps…

<function __main__.anim(size=20, fps=20)>

Make sure you understand how to save, share and create new notebooks in the environment you are working in (you might want to learn how to use git). The kernels which run the code can be changed without changing the notebook, and while Jupyter was created for Julia, Python and R (hence the name), [many languages](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) now have Jupyter kernels. Jupyter notebooks are an effective method of working and sharing code, which is why you will use this environment to do your homework. 

In the next notebook, we will start on the specifics of numerical computing and show you how to plot, simulate, integrate and sample things.